wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/train_supervised.py
    python_version: 3.10.12
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698912105.592922
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.3
      8:
      - 5
