image_root_path: /home/crohling/Documents/cell_classification/images
class_names: ["ART", "BAS", "BLA", "EBO", "EOS", "FGC", "HAC", "KSC", "LYI", "LYT", "MMZ", "MON", "MYB", "NGB",
                       "NGS", "NIF", "OTH", "PEB", "PLM", "PMO", "ABE"]